import "../globals.css";
import { i18n } from "../../localization/i18n-config";
import MainLayout from "@/layout";
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.lang}>
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
